"""initial

Revision ID: 4c8deec940b9
Revises: 
Create Date: 2025-06-24 22:43:02.856718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8deec940b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('breed_Resistance', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('games_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('games_nick_name', sa.String(length=50), nullable=False),
    sa.Column('games_status', sa.String(length=20), nullable=False),
    sa.Column('games_score', sa.Integer(), nullable=False),
    sa.Column('games_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('games_id')
    )
    op.create_table('loobys',
    sa.Column('looby_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('looby_code', sa.String(length=200), nullable=False),
    sa.Column('looby_player_1', sa.String(length=50), nullable=False),
    sa.Column('looby_player_2', sa.String(length=50), nullable=False),
    sa.Column('looby_result', sa.String(length=20), nullable=False),
    sa.Column('looby_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('looby_id'),
    sa.UniqueConstraint('looby_code')
    )
    op.create_table('power',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attack_power', sa.Integer(), nullable=False),
    sa.Column('power_effect', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_Warrior',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_password', sa.String(length=255), nullable=False),
    sa.Column('user_created', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('warriors',
    sa.Column('warrior_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warrior_name', sa.String(length=50), nullable=False),
    sa.Column('breed_fk', sa.Integer(), nullable=False),
    sa.Column('type_Warrior_fk', sa.Integer(), nullable=False),
    sa.Column('power_fk', sa.Integer(), nullable=False),
    sa.Column('warriors_health', sa.Integer(), nullable=False),
    sa.Column('warriors_energy', sa.Integer(), nullable=False),
    sa.Column('warriors_image', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['breed_fk'], ['breed.id'], ),
    sa.ForeignKeyConstraint(['power_fk'], ['power.id'], ),
    sa.ForeignKeyConstraint(['type_Warrior_fk'], ['type_Warrior.id'], ),
    sa.PrimaryKeyConstraint('warrior_id')
    )
    op.create_table('player',
    sa.Column('id_player', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('life', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=False),
    sa.Column('player_live', sa.Integer(), nullable=False),
    sa.Column('warrior_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['warrior_fk'], ['warriors.warrior_id'], ),
    sa.PrimaryKeyConstraint('id_player', 'nickname')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    op.drop_table('warriors')
    op.drop_table('users')
    op.drop_table('type_Warrior')
    op.drop_table('power')
    op.drop_table('loobys')
    op.drop_table('games')
    op.drop_table('breed')
    # ### end Alembic commands ###
